require 'fileutils'
require 'securerandom'

namespace :tmux do

	desc 'Install the .tmux.conf file'
	task :install do
		installation_target = File.join(Dir.home, '.tmux.conf')

		if File.exist?(installation_target)
			FileUtils.remove_entry(installation_target)
		end

		File.symlink(File.join(File.dirname(__FILE__), '.tmux.conf'), installation_target)
	end

end
