require 'fileutils'
require 'securerandom'

require 'duff/logger'

namespace :zsh do

	desc 'Install the .zsh* files'
	task :install do
		# The following code came from the profile/ directory
		# installation_target = File.join(Dir.home, '.profile')
		# file = File.join(File.dirname(__FILE__), '.profile')

		# Duff::LOGGER.info "Installing #{file} to #{installation_target}."

		# if File.exist?(installation_target)
		# 	Duff::LOGGER.info "#{installation_target} already exists.  Removing."

		# 	FileUtils.remove_entry(installation_target)
		# end

		# Duff::LOGGER.info "Symlinking #{file} to #{installation_target}."

		# File.symlink(file, installation_target)

		# Duff::LOGGER.info "Successful!"
	end

end
