require 'fileutils'
require 'securerandom'

namespace :emacs do

	desc 'Install the Emacs configuration'
	task :install do
		installation_target = File.join(Dir.home, '.emacs.d')
		file = File.dirname(__FILE__)

		Duff::LOGGER.info "Installing #{file} to #{installation_target}."

		if File.exist?(installation_target)
			Duff::LOGGER.info "#{installation_target} already exists.  Removing."

			FileUtils.remove_entry(installation_target)
		end

		Duff::LOGGER.info "Symlinking #{file} to #{installation_target}."

		File.symlink(File.dirname(__FILE__), installation_target)

		Duff::LOGGER.info "Successful!"
	end

end
